title: "Haoyang Wu Rain"
description: "This is Rain's blog ^_^"
baseurl: ""
url: "https://muyang233.github.io"

# 主题设置（可选）
theme: minima  # GitHub默认主题

# 导航
navigation:
  - title: Main Page
    url: /
  - title: About
    url: /about.html

# 构建设置
markdown: kramdown
plugins:
  - jekyll-feed
